export default [
  {
    id: 0,
    taskType: 'Eatery',
    title: 'lorem ipsum',
    budget: 4000,
    hasFixedBudget: true,
    qualification: 'lorem ipsum',
    equipment: 'More info',
    status: 'Pending',
    estimatedDurationHours: 1,
    owner: 'Phil Foden',
  },
  {
    id: 1,
    taskType: 'Grocery',
    title: 'lorem ipsum',
    budget: 3000,
    hasFixedBudget: false,
    qualification: 'lorem ipsum',
    equipment: 'More info',
    status: 'Assigned',
    estimatedDurationHours: 2,
    owner: 'Jose Finn',
  },
  {
    id: 3,
    taskType: 'Eatery',
    title: 'lorem ipsum',
    budget: 5000,
    hasFixedBudget: false,
    qualification: 'lorem ipsum',
    equipment: 'More info',
    status: 'Rejected',
    estimatedDurationHours: 3,
    owner: 'Kelvin Moss',
  },
  {
    id: 4,
    taskType: 'Grocery',
    title: 'lorem ipsum',
    budget: 8000,
    hasFixedBudget: true,
    qualification: 'lorem ipsum',
    equipment: 'More info',
    status: 'Canceled',
    estimatedDurationHours: 2,
    owner: 'Lens Jeph',
  },
  {
    id: 5,
    taskType: 'Eatery',
    title: 'lorem ipsum',
    budget: 3500,
    hasFixedBudget: false,
    qualification: 'lorem ipsum',
    equipment: 'More info',
    status: 'Completed',
    estimatedDurationHours: 1,
    owner: 'Matt Jones',
  },
  {
    id: 6,
    taskType: 'Grocery',
    title: 'lorem ipsum',
    budget: 5000,
    hasFixedBudget: false,
    qualification: 'lorem ipsum',
    equipment: 'More info',
    status: 'Rejected',
    estimatedDurationHours: 2,
    owner: 'Kelvin Moss',
  },
  {
    id: 7,
    taskType: 'Eatery',
    title: 'lorem ipsum',
    budget: 4000,
    hasFixedBudget: true,
    qualification: 'lorem ipsum',
    equipment: 'More info',
    status: 'Pending',
    estimatedDurationHours: 1,
    owner: 'Josh Kings',
  },
];
