export default [
  {
    id: 1,
    number: 13920,
    transactionType: 'Restaurant',
    description: 'lorem ipsum',
    amount: 4000,
    status: 'Confirmed',
    total: 4000,
    user: 'Jakes',
    ruber: 'phil',
  },
  {
    id: 2,
    number: 49302,
    transactionType: 'Grocery',
    description: 'lorem ipsum',
    amount: 3200,
    status: 'Pending',
    total: 3200,
    user: 'Kelvin',
    ruber: 'Moss',
  },
  {
    id: 3,
    number: 90382,
    transactionType: 'Task',
    description: 'lorem ipsum',
    amount: 8000,
    status: 'Confirmed',
    total: 8000,
    user: 'Luke',
    ruber: 'Matt',
  },
  {
    id: 4,
    number: 23893,
    transactionType: 'Restaurant',
    description: 'lorem ipsum',
    amount: 2500,
    status: 'Pending',
    total: 2500,
    user: 'Saint',
    ruber: 'Steve',
  },
];
