export default [
  {
    id: 1,
    email: 'jd@test.com',
    phoneNumber: '08012345678',
    password: 'jnejenjnejnjenj',
    userType: 'user',
  },
  {
    id: 2,
    email: 'sn@test.com',
    phoneNumber: '08047583920',
    password: 'dchdbdhskmdk',
    userType: 'admin',
  },
  {
    id: 3,
    email: 'kl@test.com',
    phoneNumber: '0983672819',
    password: 'dchdbdhskmdk',
    userType: 'user',
  },
  {
    id: 4,
    email: 'op@test.com',
    phoneNumber: '0981342534',
    password: 'oejenjnejeee',
    userType: 'user',
  },
  {
    id: 5,
    email: 'zp@test.com',
    phoneNumber: '0712345809',
    password: 'oejenjnejeee',
    userType: 'user',
  },
  {
    id: 6,
    email: 'pq@test.com',
    phoneNumber: '092345892',
    password: 'oejenjnejeee',
    userType: 'admin',
  },
  {
    id: 7,
    email: 'ba@test.com',
    phoneNumber: '0658930213',
    password: 'oejenjnejeee',
    userType: 'admin',
  },
];
